connector:
    name: Enhanced Connector
    jobs:
        enhanced_csv_product_export:
            title: pim_enhanced_connector.export.product.title
            type:  export
            steps:
                export:
                    title: pim_enhanced_connector.export.product.title
                    services:
                        reader:    pim_enhanced_connector.reader.product
                        processor: pim_base_connector.processor.product_to_flat_array
                        writer:    pim_base_connector.writer.file.csv_product
                    parameters:
                        batch_size: 10
        sftp_csv_category_export:
            title: pim_enhanced_connector.jobs.sftp_csv_category_export.title
            type:  export
            steps:
                export:
                    title:     pim_base_connector.jobs.csv_category_export.export.title
                    services:
                        reader:    pim_base_connector.reader.orm.category
                        processor: pim_base_connector.processor.csv_serializer.homogeneous
                        writer:    pim_enhanced_connector.writer.file.sftp


