parameters:
    pim_base_connector.processor.family_to_flat_array.class: Pim\Bundle\EnhancedConnectorBundle\Processor\FamilyToFlatArrayProcessor

services:
    pim_base_connector.processor.family_to_flat_array:
        class: %pim_base_connector.processor.family_to_flat_array.class%
        arguments:
            - '@pim_serializer.normalizer.flat.label_translation'
