parameters:
    pim_enhanced_connector.reader.product.class: Pim\Bundle\EnhancedConnectorBundle\Reader\ProductReader

services:
    pim_enhanced_connector.reader.product:
        class: %pim_enhanced_connector.reader.product.class%
        arguments:
            - '@pim_catalog.query.product_query_builder_factory'
            - '@pim_catalog.manager.channel'
            - '@pim_catalog.manager.completeness'
            - '@pim_transform.converter.metric'
            - '@doctrine.orm.default_entity_manager'
            - true
            - %akeneo_batch.entity.job_execution.class%

    pim_enhanced_connector.reader.orm.family:
        class: %pim_base_connector.reader.orm.entity.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - %pim_catalog.entity.family.class%
