parameters:
    pim_enhanced_connector.file_sender.sftp.class: Pim\Bundle\EnhancedConnectorBundle\FileSender\SftpFileSender

services:
    pim_enhanced_connector.file_sender.sftp:
        class: %pim_enhanced_connector.file_sender.sftp.class%
