parameters:
    pim_enhanced_connector.writer.file.sftp.class: Pim\Bundle\EnhancedConnectorBundle\Writer\SftpFileWriter

services:
    pim_enhanced_connector.writer.file.sftp:
        class: %pim_enhanced_connector.writer.file.sftp.class%
        arguments:
            - '@pim_enhanced_connector.file_sender.sftp'
