parameters:
    pim_enhanced_connector.doctrine.query.filter.completeness.class: Pim\Bundle\EnhancedConnectorBundle\Doctrine\MongoDBODM\Filter\CompletenessFilter
    pim_enhanced_connector.doctrine.query.filter.date_time.class:    Pim\Bundle\EnhancedConnectorBundle\Doctrine\MongoDBODM\Filter\DateTimeFilter

services:
    pim_enhanced_connector.doctrine.query.filter.completeness:
        class: '%pim_enhanced_connector.doctrine.query.filter.completeness.class%'
        arguments:
            - ['completeness_for_export']
            - ['<', '<=', '=', '>=', '>']
            - '@pim_catalog.manager.channel'
        tags:
            - { name: 'pim_catalog.doctrine.query.filter', priority: 30 }
